### PR TITLE
Improved the political messaging

### PR DESCRIPTION
**Pull request by psfree**
LGBTQ political messages are just too old-fashioned these days. Let's support a group that is really unpopular and speak truth to power. Because it doesn't matter if its hacking children's consoles, we absolutely MUST insert political messages into our home-brew.

### CODE REVIEW

**Comment by shchmue** [comment]
low effort

**Comment by psfree** [comment]
I've only reflected your own actions back at you.

**Comment by shchmue** [comment]
you made a useful program everyone was asking for to own the libs?

**Comment by sageharpuiahx** [comment]
When is the gamer edition coming out?
thejoker

**Pull request closed without merging**
